version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - php
    links:
      - php
    restart: always

  php:
    image: php:8-fpm-alpine
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%' # allow root login from any host
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts/sql-setup.sql:/docker-entrypoint-initdb.d/setup.sql
    pid: host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_ABSOLUTE_URI: /phpmyadmin
    depends_on:
      - mysql
